/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Computation */

#ifndef _Included_Computation
#define _Included_Computation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Computation
 * Method:    compute
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_Computation_compute
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
