/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LegacyBridge */

#ifndef _Included_LegacyBridge
#define _Included_LegacyBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LegacyBridge
 * Method:    gcdOfTwo
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_LegacyBridge_gcdOfTwo
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     LegacyBridge
 * Method:    gcdOfMany
 * Signature: ([J)J
 */
JNIEXPORT jlong JNICALL Java_LegacyBridge_gcdOfMany
  (JNIEnv *, jclass, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
